// Routes retired from esy.com on 2026-10-06. Their code lives in
// _archive/legacy-routes/ (see _archive/legacy-routes/README.md); the URLs
// answer 410 Gone from src/middleware.ts so search engines drop them instead
// of treating a redirect to something unrelated as a soft 404.

// Whole sections that are gone, every path beneath them included.
export const RETIRED_SECTIONS = [
  '/visual-essays',
  '/scrollytelling',
  '/photo-essays',
  '/how-to-write',
  '/how-to-write-an-essay',
  '/writing-prompts',
  '/theme-comparison',
  '/artifacts',
  '/clip-art',
  '/infographics',
  '/models',
  '/roadmap',
  '/agentic-workflows',
] as const;

// /essays itself comes back as AI marketing and tech visual essays, so only
// the old essays' first path segments are retired (a folder like 'etymology'
// retires everything under it). New essays must not reuse these slugs.
export const RETIRED_ESSAY_SLUGS = new Set<string>([
  'algorithmic-governance',
  'alphabet-adventure-train',
  'build-a-flashlight',
  'eternal-honey',
  'etymology',
  'evolution-of-mammary-glands',
  'fentanyl-crisis-timeline',
  'fentanyl-timeline',
  'flavors-of-the-east',
  'foundations',
  'geopolitics-renewable-energy',
  'gods-of-africa',
  'guides',
  'history',
  'honey-never-spoils',
  'how-a-chip-is-manufactured',
  'how-money-is-created',
  'how-to-write-a-hook',
  'inside-a-black-hole',
  'intelligence',
  'king-leopold-congo',
  'language-death',
  'mammary-gland-evolution',
  'mia-mouse-mystery-m',
  'orwells-1984',
  'pornography-etymology',
  'post-pandemic-labor',
  'rock-and-roll',
  'sammy-snail-super-speed',
  'science',
  'silk',
  'the-bitter-history-of-chocolate',
  'the-cocoa-odyssey',
  'the-deep-ocean',
  'the-diamond-cartel',
  'the-dna-helix',
  'the-firearm',
  'the-first-loaf',
  'the-fork',
  'the-geography-of-water-scarcity',
  'the-golden-crunch',
  'the-great-fire',
  'the-gridiron',
  'the-history-of-burmese-cuisine',
  'the-history-of-languages',
  'the-history-of-pizza',
  'the-holocaust',
  'the-invention-of-the-car',
  'the-invention-of-wine',
  'the-manhattan-project',
  'the-monster-under-my-bed',
  'the-night-the-stars-fell',
  'the-origin-of-animal',
  'the-origin-of-sex',
  'the-origin-of-the-word-dick',
  'the-origin-of-the-word-porn',
  'the-origin-of-the-word-sex',
  'the-origin-of-toy',
  'the-pale-blue-dot',
  'the-printing-press',
  'the-ramayana',
  'the-rwanda-genocide',
  'the-scramble-for-africa',
  'the-semiconductor-story',
  'the-silicon-revolution',
  'the-skyscraper',
  'the-speed-of-everything',
  'the-sword',
  'the-tea-journey',
  'the-tea-journey-illustrated',
  'the-thinking-machine',
  'the-train',
  'the-word-animal',
  'the-word-dick',
  'the-word-essay',
  'the-word-han',
  'the-word-pussy',
  'the-word-robot',
  'two-visions-of-tomorrow',
  'visual',
  'who-invented-basketball',
  'who-invented-high-heels',
  'who-invented-soda',
  'who-invented-the-bicycle',
  'who-invented-the-fork',
  'who-invented-the-mirror',
  'who-invented-the-sneaker',
  'who-invented-the-spoon',
  'why-venezuela-matters',
]);

/** True when a request path belongs to a retired route. */
export function isRetiredPath(pathname: string): boolean {
  const path = pathname.replace(/\/+$/, '') || '/';
  if (RETIRED_SECTIONS.some((s) => path === s || path.startsWith(s + '/'))) return true;
  const essay = path.match(/^\/essays\/([^/]+)/);
  return !!essay && RETIRED_ESSAY_SLUGS.has(essay[1]);
}
