// The brand-shapes prototypes that bring their own footer world. Plain data,
// so ConditionalFooter can check a path without loading the scenes; the
// scenes themselves load on those pages only (next/dynamic).
export const BRAND_FOOTERS = [
  'octo-hub',
  'octo-colors',
  'octo-bench',
  'bee-swarm',
  'bee-hive',
  'mycelium',
  'man-o-war',
  'octo-reef',
  'beaver-river',
  'north-star',
  'banyan',
  'clockwork',
  'orbit',
  'library',
  'octo-nursery',
  'octo-station',
  'octo-map',
  'octo-conductor',
  'octo-keeper',
  'octo-builder',
  'octo-harbor',
  'octo-sentinel',
  'octo-vault',
  'octo-coast',
  'octo-assemble',
  'octo-inspect',
  'octo-keep',
  'octo-guide',
  'octo-connect',
  'octo-polis',
  'octo-relay',
  'octo-one-reef',
  'octo-mason',
  'octo-den',
  'octo-gardener',
];
